In [ ]:
!nvidia-smi
#to find out your system cuda details

Tue May 20 20:48:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.19                 Driver Version: 561.19         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   46C    P3             15W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt

print(torch.__version__)
print(pd.__version__)

2.5.1+cu121
2.2.3


Introduction to Tensor

Creating a Tensor

In [11]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
scalar.ndim # A scalar has no dimensions

#get tensor value

scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 8, 9])
print(vector)

print(vector.ndim) # A vector has one dimension
print(vector.shape) # A vector has a shape of (3)

tensor([7, 8, 9])
1
torch.Size([3])


In [16]:
#matrix 

matrix = torch.tensor([[7,8],[9,10]])

print(matrix)
print(matrix.ndim) # A matrix has two dimensions
print(matrix.shape) # A matrix has a shape of (2, 2)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [22]:
#Tensor

ten = torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,5]]])

print(ten)
print(ten.ndim) # A tensor has three dimensions
print(ten.shape) # A tensor has a shape of (1, 3, 3)

print(ten[0]) # Accessing the first element of the tensor
print(ten[0][0]) # Accessing the first row of the first element of the tensor
print(ten[0][0][0]) # Accessing the first element of the first row of the first element of the tensor
print(ten[0][1][0]) # Accessing the first element of the second row of the first element of the tensor
print(ten[0][2][2])

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([1, 2, 3])
tensor(1)
tensor(3)
tensor(5)
