In [ ]:
!nvidia-smi
#to find out your system cuda details

Tue May 20 20:48:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.19                 Driver Version: 561.19         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   46C    P3             15W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt

print(torch.__version__)
print(pd.__version__)

2.5.1+cu121
2.2.3


Introduction to Tensor

Creating a Tensor

In [11]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
scalar.ndim # A scalar has no dimensions

#get tensor value

scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 8, 9])
print(vector)

print(vector.ndim) # A vector has one dimension
print(vector.shape) # A vector has a shape of (3)

tensor([7, 8, 9])
1
torch.Size([3])


In [16]:
#matrix 

matrix = torch.tensor([[7,8],[9,10]])

print(matrix)
print(matrix.ndim) # A matrix has two dimensions
print(matrix.shape) # A matrix has a shape of (2, 2)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [22]:
#Tensor

ten = torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,5]]])

print(ten)
print(ten.ndim) # A tensor has three dimensions
print(ten.shape) # A tensor has a shape of (1, 3, 3)

print(ten[0]) # Accessing the first element of the tensor
print(ten[0][0]) # Accessing the first row of the first element of the tensor
print(ten[0][0][0]) # Accessing the first element of the first row of the first element of the tensor
print(ten[0][1][0]) # Accessing the first element of the second row of the first element of the tensor
print(ten[0][2][2])

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([1, 2, 3])
tensor(1)
tensor(3)
tensor(5)


In [ ]:
#create a random tensor of size (3,4)
#to create 2D matrix
random_tensor = torch.rand(3,4)
print(random_tensor)

#to create 3 dimension which is known tensor
Dim3 = torch.rand(1,10,10)
print(Dim3)


tensor([[0.2513, 0.4074, 0.7381, 0.0210],
        [0.4021, 0.6255, 0.1064, 0.4919],
        [0.4626, 0.4122, 0.1918, 0.1208]])
tensor([[[0.1509, 0.0393, 0.9650, 0.0545, 0.4072, 0.0728, 0.9030, 0.9174,
          0.7390, 0.8188],
         [0.8252, 0.8545, 0.2337, 0.3620, 0.0578, 0.4795, 0.4765, 0.3038,
          0.1069, 0.2059],
         [0.0293, 0.4472, 0.1939, 0.2633, 0.6468, 0.8286, 0.2457, 0.2621,
          0.5026, 0.9135],
         [0.3723, 0.8206, 0.3376, 0.3257, 0.2146, 0.8152, 0.3711, 0.8446,
          0.6127, 0.7465],
         [0.7865, 0.8386, 0.7534, 0.5046, 0.6837, 0.1332, 0.3771, 0.3564,
          0.4699, 0.8444],
         [0.2396, 0.5909, 0.8175, 0.5096, 0.9430, 0.2270, 0.7506, 0.9360,
          0.6156, 0.2851],
         [0.1021, 0.3932, 0.2148, 0.8365, 0.7263, 0.6816, 0.5949, 0.6848,
          0.4023, 0.1996],
         [0.9628, 0.2785, 0.0319, 0.1233, 0.5253, 0.5411, 0.5267, 0.8775,
          0.3941, 0.4306],
         [0.7548, 0.3437, 0.0146, 0.3179, 0.4021, 0.2071, 0.1749,

In [8]:
#crate a random tensor with similar shape to an image tensor

img_tensor = torch.rand(size=(3,244,244))
img_tensor


tensor([[[0.1015, 0.8491, 0.8605,  ..., 0.6189, 0.2326, 0.0465],
         [0.3399, 0.6083, 0.4193,  ..., 0.6404, 0.1905, 0.1814],
         [0.8920, 0.3033, 0.9220,  ..., 0.9246, 0.0232, 0.1867],
         ...,
         [0.9047, 0.1488, 0.5440,  ..., 0.3233, 0.5490, 0.8045],
         [0.0738, 0.4143, 0.7739,  ..., 0.3941, 0.5063, 0.6981],
         [0.9687, 0.4418, 0.7054,  ..., 0.8757, 0.6333, 0.4067]],

        [[0.4137, 0.5660, 0.5580,  ..., 0.2319, 0.8154, 0.8471],
         [0.9599, 0.5447, 0.9892,  ..., 0.0582, 0.8313, 0.9571],
         [0.4286, 0.4215, 0.8390,  ..., 0.8136, 0.8110, 0.4866],
         ...,
         [0.3650, 0.0278, 0.9809,  ..., 0.4843, 0.4807, 0.0296],
         [0.1637, 0.2982, 0.7208,  ..., 0.4911, 0.7829, 0.4597],
         [0.4275, 0.8814, 0.0102,  ..., 0.8883, 0.0640, 0.2552]],

        [[0.4571, 0.1155, 0.1595,  ..., 0.8833, 0.5114, 0.5325],
         [0.5943, 0.8592, 0.3735,  ..., 0.8968, 0.8479, 0.5497],
         [0.1449, 0.9431, 0.0908,  ..., 0.6686, 0.7825, 0.

In [13]:
#create a tensor with all zeros
zero = torch.zeros(3,4)
print(zero)

#create a tensor with all ones
one = torch.ones(3,4)
print(one)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
