In [2]:
import torch

One of the most common error in deep learning : **Shape error**

In [ ]:
TENSOR1 = torch.tensor([[1,2,3],
                        [4,5,6]])

Tensor2 = torch.tensor([[1,2,3],
                         [4,5,6]])

torch.matmul(TENSOR1, Tensor2) # output: ERROR

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
torch.matmul(TENSOR1,Tensor2.T) #to get the output we can transpose the matrix

tensor([[14, 32],
        [32, 77]])

In [11]:
# note transpose matrix an tensor are different
print(f"Tensor2 (matrix): {Tensor2}")
print(f"Tensor2 (transposed): {Tensor2.T}")



Tensor2 (matrix): tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor2 (transposed): tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [12]:
#now let try using tensor

Tensor3 = torch.tensor([[[1,2,3],
                         [4,5,6]]])

print(f"Tensor3 (matrix): {Tensor3}")
print(f"Tensor3 (transposed): {Tensor3.T}")


Tensor3 (matrix): tensor([[[1, 2, 3],
         [4, 5, 6]]])
Tensor3 (transposed): tensor([[[1],
         [4]],

        [[2],
         [5]],

        [[3],
         [6]]])


**Finding the min,max,mean,sum,etc (tensor aggregation)**

In [4]:
# lets create a random vector

rm = torch.arange(0,100,10) # 0 to 100 for every 10 steps
rm

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
rm.min(), torch.min(rm)

(tensor(0), tensor(0))

In [20]:
rm.max(), torch.max(rm)

(tensor(90), tensor(90))

In [21]:
rm.mean(),torch.mean(rm) # output: error due to data type

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [23]:
rm.dtype # check data type

torch.int64

In [24]:
# to work in mean we need either float or complex dtype
rm.mean(dtype=torch.float32), torch.mean(rm.type(torch.float32)) # convert to float

(tensor(45.), tensor(45.))

In [5]:
rm.sum(), torch.sum(rm)

(tensor(450), tensor(450))

In [6]:
# Find the position of the maximum value and minimum in the tensor

rm.argmin(), torch.argmin(rm) # position of minimum value

(tensor(0), tensor(0))

In [ ]:
rm.argmax(), torch.argmax(rm) # Output: 9 this is because the idex starts with 0 

(tensor(9), tensor(9))

In [8]:
#lets try to find min max in 2D tensor
TENSOR4 = torch.tensor([[1,2,3],
                         [4,5,6]])
TENSOR4.min(), torch.min(TENSOR4) # min value

(tensor(1), tensor(1))

In [9]:
TENSOR4.max(), torch.max(TENSOR4) # max value

(tensor(6), tensor(6))

In [12]:
TENSOR4.mean(dtype=torch.float32), torch.mean(TENSOR4.type(torch.float32)) # mean value

(tensor(3.5000), tensor(3.5000))

***Reshaping, View,  Stacking***
* Reshape - reshapes the input to a defined shape 
* View - returns a view of the certain shape but keep the same memory location 
* Stacking - multiple tensor on top of each other(vstack) or side by side(hstack)

In [3]:
x = torch.arange(1.,10.)
x, x.shape # shape of the tensor

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [4]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape # reshaped tensor and its shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [6]:
x_reshape = x.reshape(3,3)
x_reshape, x_reshape.shape # reshaped tensor and its shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [8]:
x_re = x.reshape(2,3)
x_re, x_re.shape # reshaped tensor and its shape

RuntimeError: shape '[2, 3]' is invalid for input of size 9

In [9]:
# change the view
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [11]:
# changing z will change x as well because they share the same memory
z[:, 0] = 5
z,x 

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [16]:
# Stacking
x_stack = torch.stack([x,x,x,x],dim = 0)# use dim= 1
x_stack

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

***Squeezing and UnSqueezing***
* Squeeze - remove all 1 dimension from tensor
* UnSqueeze - add 1 dimension to a target tensor
* permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [18]:
x_stack.shape

torch.Size([4, 9])

In [17]:
x_stack.squeeze()

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
x_stack.squeeze().shape # it is used to remove the dimensions of size 1

torch.Size([4, 9])

In [25]:
sq = torch.rand(1,10)
sq,sq.shape

(tensor([[0.7554, 0.3878, 0.0888, 0.9431, 0.0737, 0.0547, 0.8240, 0.8234, 0.4978,
          0.2361]]),
 torch.Size([1, 10]))

In [26]:
sq.squeeze(), sq.squeeze().shape # remove the dimension of size 1

(tensor([0.7554, 0.3878, 0.0888, 0.9431, 0.0737, 0.0547, 0.8240, 0.8234, 0.4978,
         0.2361]),
 torch.Size([10]))

In [ ]:
# unsqueeze the tensor

sq.unsqueeze(0), sq.unsqueeze(0).shape # add a dimension of size 1 at the 0th index

# figure out the change in the shape 
# change 0 to 1, 2, etc in the unsqueeze to add a dimension at that index

(tensor([[[0.7554, 0.3878, 0.0888, 0.9431, 0.0737, 0.0547, 0.8240, 0.8234,
           0.4978, 0.2361]]]),
 torch.Size([1, 1, 10]))