In [4]:
import torch

One of the most common error in deep learning : **Shape error**

In [ ]:
TENSOR1 = torch.tensor([[1,2,3],
                        [4,5,6]])

Tensor2 = torch.tensor([[1,2,3],
                         [4,5,6]])

torch.matmul(TENSOR1, Tensor2) # output: ERROR

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
torch.matmul(TENSOR1,Tensor2.T) #to get the output we can transpose the matrix

tensor([[14, 32],
        [32, 77]])

In [11]:
# note transpose matrix an tensor are different
print(f"Tensor2 (matrix): {Tensor2}")
print(f"Tensor2 (transposed): {Tensor2.T}")



Tensor2 (matrix): tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor2 (transposed): tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [12]:
#now let try using tensor

Tensor3 = torch.tensor([[[1,2,3],
                         [4,5,6]]])

print(f"Tensor3 (matrix): {Tensor3}")
print(f"Tensor3 (transposed): {Tensor3.T}")


Tensor3 (matrix): tensor([[[1, 2, 3],
         [4, 5, 6]]])
Tensor3 (transposed): tensor([[[1],
         [4]],

        [[2],
         [5]],

        [[3],
         [6]]])


**Finding the min,max,mean,sum,etc (tensor aggregation)**

In [4]:
# lets create a random vector

rm = torch.arange(0,100,10) # 0 to 100 for every 10 steps
rm

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
rm.min(), torch.min(rm)

(tensor(0), tensor(0))

In [20]:
rm.max(), torch.max(rm)

(tensor(90), tensor(90))

In [21]:
rm.mean(),torch.mean(rm) # output: error due to data type

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [23]:
rm.dtype # check data type

torch.int64

In [24]:
# to work in mean we need either float or complex dtype
rm.mean(dtype=torch.float32), torch.mean(rm.type(torch.float32)) # convert to float

(tensor(45.), tensor(45.))

In [5]:
rm.sum(), torch.sum(rm)

(tensor(450), tensor(450))

In [6]:
# Find the position of the maximum value and minimum in the tensor

rm.argmin(), torch.argmin(rm) # position of minimum value

(tensor(0), tensor(0))

In [ ]:
rm.argmax(), torch.argmax(rm) # Output: 9 this is because the idex starts with 0 

(tensor(9), tensor(9))

In [8]:
#lets try to find min max in 2D tensor
TENSOR4 = torch.tensor([[1,2,3],
                         [4,5,6]])
TENSOR4.min(), torch.min(TENSOR4) # min value

(tensor(1), tensor(1))

In [9]:
TENSOR4.max(), torch.max(TENSOR4) # max value

(tensor(6), tensor(6))

In [12]:
TENSOR4.mean(dtype=torch.float32), torch.mean(TENSOR4.type(torch.float32)) # mean value

(tensor(3.5000), tensor(3.5000))

***Reshaping, View,  Stacking***
* Reshape - reshapes the input to a defined shape 
* View - returns a view of the certain shape but keep the same memory location 
* Stacking - multiple tensor on top of each other(vstack) or side by side(hstack)

In [5]:
x = torch.arange(1,10)
x, x.shape # shape of the tensor

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [6]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape # reshaped tensor and its shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [7]:
x_reshape = x.reshape(3,3)
x_reshape, x_reshape.shape # reshaped tensor and its shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [8]:
x_re = x.reshape(2,3)
x_re, x_re.shape # reshaped tensor and its shape

RuntimeError: shape '[2, 3]' is invalid for input of size 9

In [9]:
# change the view
z = x.view(3,3)
z, z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [10]:
# changing z will change x as well because they share the same memory
z[:, 0] = 5
z,x 

(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [16]:
# Stacking
x_stack = torch.stack([x,x,x,x],dim = 0)# use dim= 1 we can use the dim value if and only if the dimension is exists
x_stack

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

***Squeezing and UnSqueezing***
* Squeeze - remove all 1 dimension from tensor
* UnSqueeze - add 1 dimension to a target tensor
* permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [17]:
x_stack.shape

torch.Size([4, 9])

In [18]:
x_stack.squeeze()

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [19]:
x_stack.squeeze().shape # it is used to remove the dimensions of size 1

torch.Size([4, 9])

In [20]:
sq = torch.rand(1,10)
sq,sq.shape

(tensor([[0.2418, 0.2904, 0.0883, 0.0455, 0.1670, 0.2863, 0.8702, 0.0654, 0.5959,
          0.1801]]),
 torch.Size([1, 10]))

In [24]:
sq = sq.squeeze()
#sq.squeeze(), sq.squeeze().shape # remove the dimension of size 1
sq,sq.shape

(tensor([0.2418, 0.2904, 0.0883, 0.0455, 0.1670, 0.2863, 0.8702, 0.0654, 0.5959,
         0.1801]),
 torch.Size([10]))

In [28]:
# unsqueeze the tensor

sq.unsqueeze(dim=1), sq.unsqueeze(dim=1).shape # add a dimension of size 1 at the 0th index

# figure out the change in the shape 
# change 0 to 1, 2, etc in the unsqueeze to add a dimension at that index

(tensor([[0.2418],
         [0.2904],
         [0.0883],
         [0.0455],
         [0.1670],
         [0.2863],
         [0.8702],
         [0.0654],
         [0.5959],
         [0.1801]]),
 torch.Size([10, 1]))

In [36]:
#torch.permute() -  rearrange the dimensions of a target tensor in a specified order
per = torch.rand(size =(224,224,3))
per.size(),per

(torch.Size([224, 224, 3]),
 tensor([[[0.1468, 0.6197, 0.5661],
          [0.4151, 0.6207, 0.8900],
          [0.6886, 0.5379, 0.8394],
          ...,
          [0.3307, 0.4647, 0.3334],
          [0.8271, 0.4483, 0.9724],
          [0.4343, 0.2264, 0.5037]],
 
         [[0.5722, 0.6138, 0.6644],
          [0.9379, 0.1431, 0.7564],
          [0.8935, 0.0972, 0.0256],
          ...,
          [0.0441, 0.0033, 0.8130],
          [0.6354, 0.8338, 0.3134],
          [0.0242, 0.2958, 0.5993]],
 
         [[0.9215, 0.5726, 0.4579],
          [0.9610, 0.3595, 0.9594],
          [0.1389, 0.3689, 0.1334],
          ...,
          [0.6766, 0.8169, 0.1956],
          [0.6081, 0.8417, 0.1430],
          [0.7150, 0.5564, 0.2203]],
 
         ...,
 
         [[0.7293, 0.4139, 0.4382],
          [0.9154, 0.0730, 0.4431],
          [0.8261, 0.8801, 0.5389],
          ...,
          [0.6334, 0.4852, 0.2835],
          [0.9755, 0.5400, 0.8739],
          [0.7915, 0.8086, 0.0722]],
 
         [[0.4168, 0

In [42]:
per.permute(2,0,1) # a permute is a view means in it share the same memory, the changes will reflect in the original variable
per.size(),per

(torch.Size([3, 224, 224]),
 tensor([[[0.1468, 0.4151, 0.6886,  ..., 0.3307, 0.8271, 0.4343],
          [0.5722, 0.9379, 0.8935,  ..., 0.0441, 0.6354, 0.0242],
          [0.9215, 0.9610, 0.1389,  ..., 0.6766, 0.6081, 0.7150],
          ...,
          [0.7293, 0.9154, 0.8261,  ..., 0.6334, 0.9755, 0.7915],
          [0.4168, 0.6810, 0.8072,  ..., 0.8779, 0.6310, 0.7468],
          [0.3728, 0.9020, 0.2745,  ..., 0.4412, 0.8223, 0.1435]],
 
         [[0.6197, 0.6207, 0.5379,  ..., 0.4647, 0.4483, 0.2264],
          [0.6138, 0.1431, 0.0972,  ..., 0.0033, 0.8338, 0.2958],
          [0.5726, 0.3595, 0.3689,  ..., 0.8169, 0.8417, 0.5564],
          ...,
          [0.4139, 0.0730, 0.8801,  ..., 0.4852, 0.5400, 0.8086],
          [0.8884, 0.7950, 0.6395,  ..., 0.5920, 0.1507, 0.8799],
          [0.5582, 0.4080, 0.8090,  ..., 0.0860, 0.9765, 0.1523]],
 
         [[0.5661, 0.8900, 0.8394,  ..., 0.3334, 0.9724, 0.5037],
          [0.6644, 0.7564, 0.0256,  ..., 0.8130, 0.3134, 0.5993],
          [0

In [72]:
print(per[0,1,0].item()) 

0.572212815284729


## Indexing (selecting data from tensors)  

Indexing with pytorch is similar to idexing in Numpy

In [47]:
#create a tensor

indexing = torch.arange(1,10).reshape(1,3,3,)
indexing,indexing.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# accessing dim 1
print(indexing[0])   # entire element in the tensor
#accessing dim 2 
print(indexing[0][0])  # first row
# accessing all the three dim
print(indexing[0][0][0])  # first element in the tensor it refers to column
#note: index starts with 0 even it is one dimension we use 0 to access 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [80]:
# get all values
print(indexing[:,:,:])

# get all values of target dim
print(indexing[:,:,1])

# get all value of the 0th dimension but only the 1 index value of 1st and 2nd dimension
print(indexing[:,1,1])


print(indexing[:,1,:]) # we are doing the same thing as above but in a different way of approach

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[2, 5, 8]])
tensor([5])
tensor([[4, 5, 6]])


In [92]:
print(indexing[:,2,2]) # or indexing[0][2][2]
print(indexing[0][:][2]) # look into this problem statement
print(indexing[:,:,2]) #Exercise use this way of approach to access an element in the tensor

tensor([9])
tensor([7, 8, 9])
tensor([[3, 6, 9]])
