#Day 6 is about pinecone so i was working on it will be posted as soon as possible

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTroch tensor -> NumPy -> `torch.Tensor.numpy()`


In [1]:
#Numpy array to tensor
import torch
import numpy as np

In [ ]:
array = np.arange(1.0,8.0) 
tensor = torch.from_numpy(array) # while coverting from numpy the pytorch takes numpy's default datatype float 64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, torch.arange(1.0,8.0).dtype # difference is by default pytorch create float 32 but numpy won't

(dtype('float64'), torch.float32)

In [ ]:
tensor = tensor.type(torch.float32)
tensor.dtype #converting to FP(full precision) from double precision

torch.float32

In [10]:
#changes in numpy array, will it reflect in the tensor
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
numpy_tensor =  tensor.numpy()
tensor,numpy_tensor # Note: going from pytorch to numpy the datatype problem will occurs

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

## Reproducing (trying to take random out of random)
In short how a neural network learns:
* `start with random numbers`->`tensor operations`-> `update random numbers to try and make them better representations of the data`-> `again`->`again`..

To reduce the randomness in neural networks and Pytorch comes concept of a **random seed**.
Essentially what the random seed does in "flavour" the randomness.

In [12]:
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)
random_tensorA,random_tensorB

(tensor([[0.9750, 0.6601, 0.6820, 0.1809],
         [0.0999, 0.3313, 0.1295, 0.3698],
         [0.5030, 0.5990, 0.9661, 0.3811]]),
 tensor([[0.5017, 0.0614, 0.7067, 0.5967],
         [0.5508, 0.9556, 0.8934, 0.9540],
         [0.1380, 0.4410, 0.5265, 0.3506]]))

In [13]:
print(random_tensorA == random_tensorB)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
seed = 42
torch.manual_seed(seed) # trying to reproduce the same value while choosing random value
random_tensorC = torch.rand(3,4)

random_tensorD = torch.rand(3,4)

print(random_tensorC == random_tensorD)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.manual_seed(seed)
random_tensorC = torch.rand(3,4)
torch.manual_seed(seed)
random_tensorD = torch.rand(3,4)
print(random_tensorC == random_tensorD) 
#You have to use seed every time before using `rand` function to get same random value

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
## Running tensors and pytorch objects on the GPUs and making faster computation
torch.cuda.is_available() # to check cida is available 

True

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# its best practice to setup device agnostic since Pytorch can able to run in both `CPU` and `GPU` 

'cuda'

In [18]:
torch.cuda.device_count()

1

## Using tensors( and Models) on the GPU
we all know that the Gpu is much faster and effective incase of running a AI model its is recommended to use GPU instead of CPU.

In [ ]:
#Create a tensor (default on the CPU)
nTensor = torch.tensor([1,2,3])

#Checking CPU or GPU
print(nTensor,nTensor.device) #Therefore by default it will be in CPU

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU (if available)
nTensor = nTensor.to(device) # the device in this parameter is a variable we specified.
nTensor # since my system has GPU  it moves to cuda 
#nTensor = nTensor.to(device=device)

tensor([1, 2, 3], device='cuda:0')

In [21]:
### NumPy will only work on CPU
nTensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the Cpu issue

nTensor = nTensor.cpu().numpy() #You can use different variable to assing the numpy value so it wont affect things in GPU 
nTensor

array([1, 2, 3])