Tensor Datatypes

**Note: Tensor datatypes is one of the three big errors you'll run into with pyTorch and Deep learning:

1. Tensor not right datatype - tensor.dtype
2. Tensor not Right shape - tensor.shape
3. Tensor not on the right device - tensor.device **


In [8]:
#Float32  tensor
import torch
float_32_tensor = torch.tensor([3.0,6,0,9.0]
                                ,dtype=None,
                                device=None,
                                requires_grad=False)
print(float_32_tensor)

tensor([3., 6., 0., 9.])


In [3]:
print(float_32_tensor.dtype) #output: torch.float32

# float_16

float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor) #
print(float_16_tensor.dtype) #output: torch.float16

torch.float32
tensor([3., 6., 0., 9.], dtype=torch.float16)
torch.float16


In [8]:
#lets multiple float 16 and 32 tensor

print(float_32_tensor*float_16_tensor)

new_Tensor = torch.tensor([10,4,5,6],dtype=torch.float64)
print(new_Tensor)
print(new_Tensor.dtype) #output: torch.float64

m = new_Tensor*float_16_tensor #Note: That two different size of tensor try to multiple together will raise an error.
print(m) #the in float 64 the priority is given to the float 64 tensor



tensor([ 9., 36.,  0., 81.])
tensor([10.,  4.,  5.,  6.], dtype=torch.float64)
torch.float64
tensor([30., 24.,  0., 54.], dtype=torch.float64)


In [ ]:
#int_32
int_32_tensor = torch.tensor([3,6,0,9],
                             dtype=torch.int32,
                             device=None,
                             #device= "cuda", # we select which device we want to use cpu or Gpu
                             requires_grad=False)

## Note: that if run one tensor on cpu and other on gpu it will raise an error so try avoid it.
print(int_32_tensor)

#let try to multiple int_32 tensor with float_32 tensor
print(float_32_tensor*int_32_tensor) #output: tensor([ 9., 36.,  0., 81.], dtype=torch.float32)


tensor([3, 6, 0, 9], dtype=torch.int32)
tensor([ 9., 36.,  0., 81.])


In [12]:
#find detalis about tensor
rnd = torch.rand(4,4)
print(rnd)
print(f"Dtype: {rnd.dtype}")
print(f"Shape: {rnd.shape}")
print(f"Device: {rnd.device}")

tensor([[0.6097, 0.6954, 0.4387, 0.3101],
        [0.6209, 0.9026, 0.7047, 0.7687],
        [0.5271, 0.9465, 0.1596, 0.6354],
        [0.8421, 0.3223, 0.1141, 0.5319]])
Dtype: torch.float32
Shape: torch.Size([4, 4])
Device: cpu


### Manipulating Tensor

* Addition
* Subraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication (Dot product)


In [3]:
# create a tensor

sample_Tensor = torch.tensor([[[1,2,3],
                               [4,5,6],
                               [7,8,9]]])
sample_Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
sample_Tensor+10

tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [ ]:
sample_Tensor*10 # all the previous operation will not affected to the original variable or tensor

tensor([[[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])

In [16]:
sample_Tensor -10

tensor([[[-9, -8, -7],
         [-6, -5, -4],
         [-3, -2, -1]]])

In [17]:
sample_Tensor/10

tensor([[[0.1000, 0.2000, 0.3000],
         [0.4000, 0.5000, 0.6000],
         [0.7000, 0.8000, 0.9000]]])

In [18]:
## Now there is another way to do this operation
sample_Tensor.add_(10) # this will add 10 to the original tensor

tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [ ]:
sample_Tensor.mul(10) # And using this method the original tensor will be affected

tensor([[[110, 120, 130],
         [140, 150, 160],
         [170, 180, 190]]])

#Now lets dive into Matrix multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning are:

* Element-wise multiplication 
* Matrix multiplication (dot product)


In [21]:
sh = sample_Tensor.shape
sh

torch.Size([1, 3, 3])

In [22]:
sh[0]

1

In [23]:
sh[1]

3

In [24]:
sh[2]

3

In [6]:
%%time
torch.matmul(sample_Tensor,sample_Tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])

In [9]:
%%time
#create a matrix
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
print(matrix)
#matrix multiplication
print(torch.matmul(matrix, matrix))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
CPU times: total: 0 ns
Wall time: 5 ms


In [10]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

There are two main rules that perform matrix multiplication without any error:
1. The **innner dimensions** must match:
 * `(3,2) @ (3,2)` won't work
 * `(2,3) @ (3,2)` will work
 * `(3,2) @ (2,3)` will work
The column of first matrix and row of second matrix should be same 

2. The resulting matrix has the shape of the **outer dimensions**:
    * `(2,3) @ (3,2)` -> `(2,2)`
    * `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(3,2)) #output : error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)